"""add Department

Revision ID: 3137a680d98d
Revises: 857e7ab4b422
Create Date: 2024-06-30 15:38:24.487771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3137a680d98d'
down_revision = '857e7ab4b422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
